[hello]
hello = "hello ${name}."

[shakespeare]
shakespeare = "${data}"

[version]
version = "${repo} (${tag}, on ${revision})"

[uptime]
uptime = "${room} has been live for ${uptime}."
offline = "${room} appears to be offline."

[viewers]
viewers = "there are ${count} viewers."
no_viewers = "noone is watching :("
offline = "${channel} is offline"

[crates]
not_exact = "closest match: ${name} = ${version}"
crate_vers = "${name} = ${version}"
description = "${description}"
links = "${repo} | ${docs}"
unknown = "I couldn't find a crate matching '${name}'"
no_crate = "a crate name must be provided"

[whatsong]
current = "${title} | ${url}?ts=${timestamp}"
previous = "${title} | ${url}"
no_song = "no song is playing (probably)"

[user_defined]
error_reserved_name = "${command} is a reserved name"
error_already_exists = "${command} already exists"
error_command_not_found = "${command} wasn't found"
error_insufficient_privlege = "you cannot do that to ${command}"
error_missing_head = "you must provide a '!command'"
error_missing_tail = "you must provide a body for '${head}'"

added = "added command: ${command}"
edited = "edited command: ${command}"
renamed = "renamed ${from} to ${to}"
deleted = "that command has been deleted"
say = "${data}"

command_description = "${command} -- ${body}"
command_created_at = "created by ${owner}. used ${uses} times."
